package com.jfinal.club.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		arp.addMapping("ml_address", "id", MlAddress.class);
		arp.addMapping("ml_attribute", "id", MlAttribute.class);
		arp.addMapping("ml_coupon", "id", MlCoupon.class);
		arp.addMapping("ml_goods", "id", MlGoods.class);
		arp.addMapping("ml_goods_type", "id", MlGoodsType.class);
		arp.addMapping("ml_mall", "id", MlMall.class);
		arp.addMapping("ml_order", "id", MlOrder.class);
		arp.addMapping("ml_params", "id", MlParams.class);
		arp.addMapping("ml_pay_log", "id", MlPayLog.class);
		arp.addMapping("ml_resource", "id", MlResource.class);
		arp.addMapping("ml_shopping_cart", "id", MlShoppingCart.class);
		arp.addMapping("ml_user", "id", MlUser.class);
		arp.addMapping("ml_user_coupon", "id", MlUserCoupon.class);
		arp.addMapping("ml_userlogin_log", "id", MlUserloginLog.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("session", "id", Session.class);
	}
}

