package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlAddress extends BaseMlAddress<MlAddress> {
	
}
