package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlAttribute extends BaseMlAttribute<MlAttribute> {
	
}
