package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlCoupon extends BaseMlCoupon<MlCoupon> {
	
}
