package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlGoods extends BaseMlGoods<MlGoods> {

    public void setRemark(java.lang.String remark) {
        set("remark", remark);
    }

    public java.lang.String getRemark() {
        return getStr("remark");
    }
	
}
