package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlGoods extends BaseMlGoods<MlGoods> {
	
}
