package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlGoodsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlGoodsType extends BaseMlGoodsType<MlGoodsType> {
	
}
