package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlMall;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlMall extends BaseMlMall<MlMall> {
	
}
