package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlOrder extends BaseMlOrder<MlOrder> {
}
