package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlParams extends BaseMlParams<MlParams> {
	
}
