package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlPayLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlPayLog extends BaseMlPayLog<MlPayLog> {
	
}
