package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlResource extends BaseMlResource<MlResource> {
	
}
