package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlShoppingCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlShoppingCart extends BaseMlShoppingCart<MlShoppingCart> {
	
}
