package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlUserCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlUserCoupon extends BaseMlUserCoupon<MlUserCoupon> {
	
}
