package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMlUserloginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MlUserloginLog extends BaseMlUserloginLog<MlUserloginLog> {
	
}
