package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMlCoupon<M extends BaseMlCoupon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCouponType(java.lang.Integer couponType) {
		set("coupon_type", couponType);
	}
	
	public java.lang.Integer getCouponType() {
		return getInt("coupon_type");
	}

	public void setCouponAmount(java.lang.Integer couponAmount) {
		set("coupon_amount", couponAmount);
	}
	
	public java.lang.Integer getCouponAmount() {
		return getInt("coupon_amount");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setUseAmount(java.lang.Integer useAmount) {
		set("use_amount", useAmount);
	}
	
	public java.lang.Integer getUseAmount() {
		return getInt("use_amount");
	}

	public void setEffectiveDays(java.lang.Integer effectiveDays) {
		set("effective_days", effectiveDays);
	}
	
	public java.lang.Integer getEffectiveDays() {
		return getInt("effective_days");
	}

	public void setCouponNumber(java.lang.Integer couponNumber) {
		set("coupon_number", couponNumber);
	}
	
	public java.lang.Integer getCouponNumber() {
		return getInt("coupon_number");
	}

	public void setPerReceiveNumber(java.lang.Integer perReceiveNumber) {
		set("per_receive_number", perReceiveNumber);
	}
	
	public java.lang.Integer getPerReceiveNumber() {
		return getInt("per_receive_number");
	}

	public void setExpireDate(java.util.Date expireDate) {
		set("expire_date", expireDate);
	}
	
	public java.util.Date getExpireDate() {
		return get("expire_date");
	}

	public void setTargetType(java.lang.Integer targetType) {
		set("target_type", targetType);
	}
	
	public java.lang.Integer getTargetType() {
		return getInt("target_type");
	}

	public void setTargetNumber(java.lang.String targetNumber) {
		set("target_number", targetNumber);
	}
	
	public java.lang.String getTargetNumber() {
		return getStr("target_number");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModifier(java.lang.Integer modifier) {
		set("modifier", modifier);
	}
	
	public java.lang.Integer getModifier() {
		return getInt("modifier");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCurrentMallId(java.lang.Integer currentMallId) {
		set("current_mall_id", currentMallId);
	}
	
	public java.lang.Integer getCurrentMallId() {
		return getInt("current_mall_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
