package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMlMall<M extends BaseMlMall<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMallName(java.lang.String mallName) {
		set("mall_name", mallName);
	}
	
	public java.lang.String getMallName() {
		return getStr("mall_name");
	}

	public void setMallDesc(java.lang.String mallDesc) {
		set("mall_desc", mallDesc);
	}
	
	public java.lang.String getMallDesc() {
		return getStr("mall_desc");
	}

	public void setMallCode(java.lang.Integer mallCode) {
		set("mall_code", mallCode);
	}
	
	public java.lang.Integer getMallCode() {
		return getInt("mall_code");
	}

	public void setMallType(java.lang.String mallType) {
		set("mall_type", mallType);
	}
	
	public java.lang.String getMallType() {
		return getStr("mall_type");
	}

	public void setMallAddress(java.lang.String mallAddress) {
		set("mall_address", mallAddress);
	}
	
	public java.lang.String getMallAddress() {
		return getStr("mall_address");
	}

	public void setMallPhone(java.lang.String mallPhone) {
		set("mall_phone", mallPhone);
	}
	
	public java.lang.String getMallPhone() {
		return getStr("mall_phone");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModifier(java.lang.Integer modifier) {
		set("modifier", modifier);
	}
	
	public java.lang.Integer getModifier() {
		return getInt("modifier");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
