package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMlGoods<M extends BaseMlGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGoodsCode(java.lang.String goodsCode) {
		set("goods_code", goodsCode);
	}
	
	public java.lang.String getGoodsCode() {
		return getStr("goods_code");
	}

	public void setGoodsTypeId(java.lang.Integer goodsTypeId) {
		set("goods_type_id", goodsTypeId);
	}
	
	public java.lang.Integer getGoodsTypeId() {
		return getInt("goods_type_id");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	public void setGoodsIntroduce(java.lang.String goodsIntroduce) {
		set("goods_introduce", goodsIntroduce);
	}
	
	public java.lang.String getGoodsIntroduce() {
		return getStr("goods_introduce");
	}

	public void setOrder(java.lang.Integer order) {
		set("order", order);
	}
	
	public java.lang.Integer getOrder() {
		return getInt("order");
	}

	public void setPrice(java.lang.Integer price) {
		set("price", price);
	}
	
	public java.lang.Integer getPrice() {
		return getInt("price");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}
	
	public java.lang.Integer getCount() {
		return getInt("count");
	}

	public void setGoodsDetail(java.lang.String goodsDetail) {
		set("goods_detail", goodsDetail);
	}
	
	public java.lang.String getGoodsDetail() {
		return getStr("goods_detail");
	}

	public void setDetailPicture(java.lang.String detailPicture) {
		set("detail_picture", detailPicture);
	}
	
	public java.lang.String getDetailPicture() {
		return getStr("detail_picture");
	}

	public void setBannerPicture(java.lang.String bannerPicture) {
		set("banner_picture", bannerPicture);
	}
	
	public java.lang.String getBannerPicture() {
		return getStr("banner_picture");
	}

	public void setSellingTime(java.util.Date sellingTime) {
		set("selling_time", sellingTime);
	}
	
	public java.util.Date getSellingTime() {
		return get("selling_time");
	}

	public void setStoppingTime(java.util.Date stoppingTime) {
		set("stopping_time", stoppingTime);
	}
	
	public java.util.Date getStoppingTime() {
		return get("stopping_time");
	}

	public void setGoodsAttribute(java.lang.String goodsAttribute) {
		set("goods_attribute", goodsAttribute);
	}
	
	public java.lang.String getGoodsAttribute() {
		return getStr("goods_attribute");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModifier(java.lang.Integer modifier) {
		set("modifier", modifier);
	}
	
	public java.lang.Integer getModifier() {
		return getInt("modifier");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCurrentMallId(java.lang.Integer currentMallId) {
		set("current_mall_id", currentMallId);
	}
	
	public java.lang.Integer getCurrentMallId() {
		return getInt("current_mall_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
