package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMlAddress<M extends BaseMlAddress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setAddressxy(java.lang.String addressxy) {
		set("addressxy", addressxy);
	}
	
	public java.lang.String getAddressxy() {
		return getStr("addressxy");
	}

	public void setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
	}
	
	public java.lang.Integer getIsDefault() {
		return getInt("is_default");
	}

	public void setReceiveAddress(java.lang.String receiveAddress) {
		set("receive_address", receiveAddress);
	}
	
	public java.lang.String getReceiveAddress() {
		return getStr("receive_address");
	}

	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}
	
	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}
	
	public java.lang.String getZipcode() {
		return getStr("zipcode");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("provinceId", provinceId);
	}
	
	public java.lang.Integer getProvinceId() {
		return getInt("provinceId");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("cityId", cityId);
	}
	
	public java.lang.Integer getCityId() {
		return getInt("cityId");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("districtId", districtId);
	}
	
	public java.lang.Integer getDistrictId() {
		return getInt("districtId");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModifier(java.lang.Integer modifier) {
		set("modifier", modifier);
	}
	
	public java.lang.Integer getModifier() {
		return getInt("modifier");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCurrentMallId(java.lang.Integer currentMallId) {
		set("current_mall_id", currentMallId);
	}
	
	public java.lang.Integer getCurrentMallId() {
		return getInt("current_mall_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
